name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7.1
    - name: Setup database
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        RAILS_ENV: test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: bundle exec rake db:setup
    - name: Run tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        RAILS_ENV: test
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
      run: bundle exec rspec
